import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Web3Modal from "@/utils/WalletProvider";
import Navbar from "@/components/Navbar";

const Poppin = Poppins({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Poppin.className}>
        <Navbar />
        <Web3Modal>{children}</Web3Modal>
      </body>
    </html>
  );
}
