import "./globals.css";
import type { Metadata } from "next";
import local from "next/font/local";
import WalletProvider from "@/providers/walletProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const font = local({
  src: "../components/dmsans/DMSans-Regular.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-US">
      <body className={`${font.className}`}>
        <WalletProvider>
          <Navbar />
          <div>{children}</div>
          <Footer />
        </WalletProvider>
      </body>
    </html>
  );
}
